import { MediaItem, LogEntry } from './types';

export const MOCK_MEDIA: MediaItem[] = [
  {
    id: '1',
    title: 'Cosmic Drift',
    year: 2023,
    type: 'movie',
    posterUrl: 'https://picsum.photos/300/450?random=1',
    backdropUrl: 'https://picsum.photos/1280/720?random=1',
    plot: 'A lone astronaut discovers a signal from the edge of the universe that contradicts all known physics.',
    duration: '2h 14m',
    rating: 'PG-13',
    quality: '4K HDR',
  },
  {
    id: '2',
    title: 'Neon Nights',
    year: 2024,
    type: 'tv',
    posterUrl: 'https://picsum.photos/300/450?random=2',
    backdropUrl: 'https://picsum.photos/1280/720?random=2',
    plot: 'In a city that never sleeps, a detective and a hacker team up to solve cyber-crimes.',
    duration: '45m',
    rating: 'TV-MA',
    quality: '1080p',
  },
  {
    id: '3',
    title: 'The Mountain Core',
    year: 2022,
    type: 'movie',
    posterUrl: 'https://picsum.photos/300/450?random=3',
    backdropUrl: 'https://picsum.photos/1280/720?random=3',
    plot: 'An expedition into the earth goes wrong when they discover a civilization beneath the crust.',
    duration: '1h 55m',
    rating: 'R',
    quality: '1080p',
  },
  {
    id: '4',
    title: 'Silicon Valley Dreams',
    year: 2021,
    type: 'tv',
    posterUrl: 'https://picsum.photos/300/450?random=4',
    backdropUrl: 'https://picsum.photos/1280/720?random=4',
    plot: 'A documentary style look at the early days of the internet boom.',
    duration: '50m',
    rating: 'TV-14',
    quality: '1080p',
  },
  {
    id: '5',
    title: 'Ocean Blue',
    year: 2023,
    type: 'movie',
    posterUrl: 'https://picsum.photos/300/450?random=5',
    backdropUrl: 'https://picsum.photos/1280/720?random=5',
    plot: 'A deep dive into the mysteries of the Pacific Ocean.',
    duration: '1h 30m',
    rating: 'G',
    quality: '4K',
  },
  {
    id: '6',
    title: 'Cyber Punk Reality',
    year: 2024,
    type: 'tv',
    posterUrl: 'https://picsum.photos/300/450?random=6',
    backdropUrl: 'https://picsum.photos/1280/720?random=6',
    plot: 'Virtual reality is no longer distinguishable from real life.',
    duration: '1h',
    rating: 'TV-MA',
    quality: '4K HDR',
  },
];

export const INITIAL_LOGS: LogEntry[] = [
  { id: '1', timestamp: '10:00:01', level: 'INFO', message: 'Server started on port 8096', source: 'SYSTEM' },
  { id: '2', timestamp: '10:00:02', level: 'INFO', message: 'DLNA Service initialized', source: 'DLNA' },
  { id: '3', timestamp: '10:00:02', level: 'INFO', message: 'SSDP Broadcasting on 239.255.255.250', source: 'DLNA' },
  { id: '4', timestamp: '10:00:05', level: 'INFO', message: 'Scanning /media/movies...', source: 'SCANNER' },
  { id: '5', timestamp: '10:00:15', level: 'INFO', message: 'Found 14 new files', source: 'SCANNER' },
];

export const MOCK_BANDWIDTH_DATA = [
  { time: '10:00', mbps: 12 },
  { time: '10:05', mbps: 18 },
  { time: '10:10', mbps: 8 },
  { time: '10:15', mbps: 25 },
  { time: '10:20', mbps: 45 },
  { time: '10:25', mbps: 30 },
  { time: '10:30', mbps: 60 },
];